version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: healthaid_db
      POSTGRES_USER: healthaid_user
      POSTGRES_PASSWORD: healthaid_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn healthaid.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=False
      - DATABASE_URL=postgresql://healthaid_user:healthaid_password@db:5432/healthaid_db
      - SECRET_KEY=rvVlWu72GezWW5ofxldE3p4LgszaajWTrx7MpUQd0lmU-AFo1vsUvt_mFq-aQyig5Ow
      - ALLOWED_HOSTS=localhost,127.0.0.1

volumes:
  postgres_data:
  staticfiles:
